### ISSUE TITLE
can i make the elbow function vertical?

### ISSUE THREAD

**Issue by blu94** [justincy/d3-pedigree-examples#11]
Can i make this function become vertical?
this is the elbow function for horizontal 
function elbow(d) {
          return "M" + d.source.y + "," + d.source.x
            + "H" + (d.source.y + (d.target.y-d.source.y)/2)
            + "V" + d.target.x
            + "H" + d.target.y;
        }

**Comment by justincy** [comment]
The third bullet point in the Notes section of the Readme explains how to make the chart display vertically. Basically just switch the x and y values so that their in the normal Cartesian order (they are currently swapped to enable the horizontal display). The x and y will need to be changed throughout the code, including the elbow function.
