### ISSUE TITLE
Trying to expand children/parent on every node

### ISSUE THREAD

**Issue by mexin** [justincy/d3-pedigree-examples#14]
Hey Justin, opened this issue to see if there's a possibility on expanding/collapsing children/parent tree on every node from a family tree.

Thanks for your help! 

Attached a image for more visual understanding.
![d3familytree-question](https://cloud.githubusercontent.com/assets/3453330/18393237/3df5d8b6-767a-11e6-9e2e-c000d1df0527.png)

**Comment by justincy** [comment]
Thanks for the visual. That helps a lot.

Drawing children requires creating a new d3 tree. Each person you want to draw children for needs their own d3 tree. The main issue is that d3 trees are not aware of each other and thus won't adjust their layout like a single d3 tree can do for it's own nodes. 

For example, where would you draw the 3 children of Mary August Hickey? There's no room for them.

The easiest way around this is to require that a person be the root node in order to display their descendants. So instead of drawing Joseph's children in place, you move Joseph to the root and redraw the entire pedigree.

You may also consider a simplified form of displaying the children that FamilySearch does as shown in the picture below.

![image](https://cloud.githubusercontent.com/assets/1037458/18393934/25fba4a4-767d-11e6-9663-8abd8f3d670e.png)

Instead of adding children to the tree they allow the children to be expanded in a list. Clicking on one of the children would allow you to redraw the tree with them at the root.

Does that all make sense? Do you have any other questions?

**Comment by mexin** [comment]
Thanks for clarifying my doubts Justin! 

Makes sense, so yeah, achieving what I'm trying to do it's gonna be a nightmare. Will look further on the examples you showed!
